### PR TITLE
Updating to the Last Frame Image

### PR DESCRIPTION
**Pull request by xMatador-Git**
Should be the last frame before the white pixel chaos starts

Image by opl_

https://www.reddit.com/r/place/comments/twhrf4/final_rplace_2022_canvas_before_my_scraper/

### CODE REVIEW

**Comment by DRKSLV** [comment]
Eventually this project should (probably) move to using an image from a restauration project such as:
https://www.reddit.com/r/thefinalclean/
This would make the intent of the artists in the final canvas more clearer for this explanation project.

For now, this is probably the most accurate end state!
(Also someone needs to remove explanations for past versions of the canvas, like the one mogus that was obliterated days ago)

**Comment by xMatador-Git** [comment]
> Eventually this project should (probably) move to using an image from a restauration project such as: https://www.reddit.com/r/thefinalclean/ This would make the intent of the artists in the final canvas more clearer for this explanation project.
> 
> For now, this is probably the most accurate end state! (Also someone needs to remove explanations for past versions of the canvas, like the one mogus that was obliterated days ago)

well it will take some time to comptes process all the reddit posts/pull requests

**Comment by DRKSLV** [comment]
This is not a submission though? 
@ab-gh

**Comment by ab-gh** [comment]
> @ab-gh

Apologies for that. We have already changed to a final image I believe - if you have a more recent image that what we are using, please reopen the PR.

**Comment by opl-** [comment]
Copied from the comments on my Reddit post:

I was running a program to save all data sent by Reddit throughout the event. My program received the message telling it to switch to the white only palette at 22:47:31 UTC.

Files used (last full frames received before config change received at 1649112450989 and 1649112451013):

https://hot-potato.reddit.com/media/canvas-images/1649112450736-0-f-p8WJC8gp.png

https://hot-potato.reddit.com/media/canvas-images/1649112450717-1-f-ZBu5lxtz.png

https://hot-potato.reddit.com/media/canvas-images/1649112450738-2-f-Oq1IAWrM.png

https://hot-potato.reddit.com/media/canvas-images/1649112450939-3-f-asYsAbV9.png

Here's a link to the raw data surrounding the configuration update for the nerds among us. I'll publish all my raw data after I package it up.

https://cdn.discordapp.com/attachments/429823324210593793/960698306261028904/ws-white-palette.json

**Pull request closed without merging**
