### PR TITLE
Fix broken formatting

### PR DESCRIPTION
**Pull request by m654z**

### CODE REVIEW

**Comment by maltejur** [comment]
What formatting is broken?

**Comment by m654z** [comment]
> 

My previous comment changed the title to "2022 r/place atlas", which caused some word wrapping issues. I'm just changing it back here

**Review by ab-gh — APPROVED** [review]

**Comment by maltejur** [comment]
Oh hm weird everything worked fine for me on windows and linux and on firefox and chromium.

Screenshot_20220405_221725

Wouldn't the easier fix have been decreasing the font size?

**Comment by maltejur** [comment]
Hmm [according to the guy](https://github.com/Codixer/place-atlas/issues/523#issuecomment-1089395585) who opened the issue, the [preview deployment](https://deploy-preview-443--place-atlas.netlify.app/), which should have been exactly the same, worked for him, so I think everything was fine and the CSS was just still cached for him or something like that.

**Comment by Wayland-Smithy** [comment]
Yep slapped around my cache a bit and now have the proper `font-size` CSS on the prod deployment. 🚀

**Pull request merged**
