### PR TITLE
Fixed some translation issues

### PR DESCRIPTION
**Pull request by sbritorodr**
Archipielago --> Islands
comprises --> Produces

### CODE REVIEW

**Comment by sbritorodr** [comment]
Somehow my PR has conflicts with the branch for no apparent reason. I don't really understand the [README.md](README.md) file, so if I did this PR wrong because I didn't commit in the cleanup branch (in my fork), maybe we should add a more specific instructions in the readme file.

**Comment by Codixer** [comment]
Please fix the conflicts above by merging cleanup into your branch ^

**Comment by sbritorodr** [comment]
Okay, in which branch do I need to make the changes? In `sbritorodr/place-atlas:master` or `sbritorodr/place-atlas:cleanup` ?

**Comment by sbritorodr** [comment]
I think it's fixed now!

**Comment by ab-gh** [comment]
Thank you for the contribution. This PR is now behind cleanup; please create a new branch, commit just the relevant changes, and open a new PR

**Pull request closed without merging**
