### PR TITLE
Add r/Philippines entries

### PR DESCRIPTION
**Pull request by xyr11**
Handles entries for the following submissions: (some are slightly edited for clarity)

Flag: https://www.reddit.com/r/placeAtlas2/comments/twkttk/entry_for_rph/
Snoo mascot: https://www.reddit.com/r/placeAtlas2/comments/twjfna/new_submission/
Pisay: https://www.reddit.com/r/placeAtlas2/comments/twiy9i/new_submission/
DLSU & Ateneo: https://www.reddit.com/r/placeAtlas2/comments/twhqui/new_submission_from_rphilippines/
Leni & Kiko: https://www.reddit.com/r/placeAtlas2/comments/twhp2g/lenikiko_banner_information/
Another flag: https://www.reddit.com/r/placeAtlas2/comments/twi405/new_submission_ph1/

### CODE REVIEW

**Comment by Aikoyori** [comment]
I already had a few entries in #259 with aid from Discord. There are a few things missing in mine so this should compliment things.

**Comment by Tais993** [comment]
Some of these have already been added, and conflicts with #373 may exist.
Could you (@xyr11) update your PR, and handle possible conflicts with @Aikoyori (so the best ones stay)

**Comment by xyr11** [comment]
Sure! I'm planning to create a new pull request so that I can include stuff from the latest commit. It's been 6 hours and a lot has changed so I may need to catch up a little bit.

**Comment by Tais993** [comment]
Some things changed, if you're gonna create a new PR I'd use the Reddit instead.
PR's are only accepted for edits now, [see here.](https://www.reddit.com/r/placeAtlas2/comments/twteic/submissions_may_only_be_made_though_reddit_we/)

**Pull request closed without merging**
